### ISSUE TITLE
Incorrect number of energy states in the case of 3x3 matrix

### ISSUE THREAD

**Issue by iamashwin99** [tonymenzo/Wang-Landau_2DIsing#1]
Thanks for the code to run the Wang Landau algorithm on 2d Ising model on cpp, it helped me to get an idea of the structure.
However theoretically for a 3x3 matrix, we are supposed to get more than 5 energy states however on running  your code with ` L = 3`, the g_E.dat  file contains only 3 energy states namely
|#  |E              |g(E)          |TotalSamplingsHistogram|
|---|---------------|--------------|-----------------------|
|   |-2.000000000000|0.360412701557|268729                 |
|   |0.000000000000 |0.667703944026|268844                 |
|   |2.000000000000 |0.350263098509|269697                 |

Any idea why we are missing the other states? I am supposing it is because of the pseudo-random number sampling.
Thankyou in advance

**Comment by tonymenzo** [comment]
The number of energy states is heavily dependent on the way boundaries the boundaries are defined. With how I've defined then in line 372 of `ising_model_WL.cpp` there are only 3 energy states.

**Comment by tonymenzo** [comment]
The number of energy states is dependent on how the boundaries are defined. Here the energy is computed with a free boundary boundary condition (see line 372 of `ising_model_WL.cpp` for more details on how the energy is computed for a given lattice configuration). For a 3x3 lattice this gives three distinct energy states.
